"""Core capture module.

This module is intentionally self-contained so it can run independently of the
rest of the Smart-Storage-AR project.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import time


class CaptureError(RuntimeError):
    """Raised when frame capture fails."""


@dataclass
class CaptureResult:
    """Represents an output image generated by the capture module."""

    output_path: Path
    source: str
    width: int
    height: int


class CaptureModule:
    """Capture component that supports webcam and synthetic frame capture."""

    def capture(
        self,
        output_path: str | Path,
        source: str = "synthetic",
        device_index: int = 0,
        timeout_seconds: float = 5.0,
    ) -> CaptureResult:
        """Capture a frame and write it to disk."""
        out = Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)

        if source == "synthetic":
            final_path, width, height = self._write_synthetic_ppm(out)
            return CaptureResult(final_path, source, width, height)

        if source == "webcam":
            return self._capture_from_webcam(out, device_index, timeout_seconds)

        raise CaptureError(f"Unsupported source '{source}'. Use 'synthetic' or 'webcam'.")

    def _capture_from_webcam(
        self,
        output_path: Path,
        device_index: int,
        timeout_seconds: float,
    ) -> CaptureResult:
        """Capture a single frame from webcam using OpenCV when available."""
        try:
            import cv2  # type: ignore
        except Exception as exc:  # pragma: no cover - runtime environment dependent
            raise CaptureError(
                "OpenCV is required for webcam capture. Install opencv-python or use '--source synthetic'."
            ) from exc

        cap = cv2.VideoCapture(device_index)
        if not cap.isOpened():
            raise CaptureError(f"Could not open webcam at index {device_index}.")

        deadline = time.time() + max(timeout_seconds, 0.1)
        frame = None
        while time.time() < deadline:
            ok, frame = cap.read()
            if ok and frame is not None:
                break
            time.sleep(0.05)

        cap.release()

        if frame is None:
            raise CaptureError("Timed out while trying to read a webcam frame.")

        if not cv2.imwrite(str(output_path), frame):
            raise CaptureError(f"Failed to write captured frame to '{output_path}'.")

        height, width = frame.shape[:2]
        return CaptureResult(output_path, "webcam", width, height)

    def _write_synthetic_ppm(self, output_path: Path) -> tuple[Path, int, int]:
        """Write a deterministic synthetic image in PPM format using stdlib only."""
        width, height = 320, 240

        if output_path.suffix.lower() != ".ppm":
            output_path = output_path.with_suffix(".ppm")

        with output_path.open("wb") as f:
            f.write(f"P6\n{width} {height}\n255\n".encode("ascii"))
            for y in range(height):
                for x in range(width):
                    r = int((x / width) * 255)
                    g = int((y / height) * 255)
                    b = int(((x + y) / (width + height)) * 255)
                    f.write(bytes((r, g, b)))

        return output_path, width, height
